# This is a basic workflow to help you get started with MATLAB Actions

name: Build and Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # Sets up MATLAB on a GitHub-hosted runner
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2.3.0

      # Open the MATLAB project
      - name: Open MATLAB project
        uses: matlab-actions/run-command@v2.1.1
        with:
          command: openProject('MATLAB/Solvers.prj');

      # Runs a set of commands using the runners shell
      - name: Run all tests
        uses: matlab-actions/run-tests@v2.1.1
        with:
          source-folder: MATLAB/src
          code-coverage-cobertura: code-coverage/coverage.xml

      # Upload code coverage report
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: VEXLife/Solvers
